name: MGMobEscape
main: com.comze_instancelabs.mgmobescape.Main
version: 1.6.0
author: instancelabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   dragonescape:
      description: Main command
      usage: /dragonescape <action>
      aliases: [de]
   escapethemob:
      description: Main command
      usage: /escapethemob <action>
      aliases: [etm]
